#!/bin/sh

docker build $@ -t xavren/php:7 ./nginx-php7/
docker build $@ -t xavren/php:5.6 ./nginx-php56/
docker build $@ -t xavren/symfony:5.6 ./symfony-php56
docker build $@ -t xavren/symfony:7 ./symfony-php7
